/*
 * test.pb.h
 *
 *  Created on: Feb 15, 2025
 *      Author: Dell
 */

/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_FILES_TEST_PB_H_INCLUDED
#define PB_PROTO_FILES_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TestMessage {
    int32_t id;
    float temperature;
    float humidity;
    int64_t timestamp;
} TestMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TestMessage_init_default                 {0, 0, 0, 0}
#define TestMessage_init_zero                    {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TestMessage_id_tag                       1
#define TestMessage_temperature_tag              2
#define TestMessage_humidity_tag                 3
#define TestMessage_timestamp_tag                4

/* Struct field encoding specification for nanopb */
#define TestMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         4)
#define TestMessage_CALLBACK NULL
#define TestMessage_DEFAULT NULL

extern const pb_msgdesc_t TestMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TestMessage_fields &TestMessage_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_FILES_TEST_PB_H_MAX_SIZE           TestMessage_size
#define TestMessage_size                         32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif


